### ISSUE TITLE
Synchronize Core Subject Thesaurus from Libraries Canada to 3.12 (backport to 3.10 and 3.6)

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#214] opened 2021-05-12 14:36 UTC
We noticed that Ian has a newer core subject thesaurus than is use on the `3.6.x` branch. This issue is to commit any thesaurus files that are needed to version control `3.12.x` branch, and backport to `3.6.x`.

* https://canada.multites.net/cst/def.asp?lang=En&n=E5807AB0-1
* Change log: https://canada.multites.net/cst/def.asp?lang=En&n=B1B9013A-1

Minimal processing needed, linefeeds need to be changed to commit to git repo.

**Comment by ianwallen** [comment] 2021-05-12 23:18
@jodygarnett 
Is this a duplicate of #212?

**Comment by jodygarnett** [comment] 2021-05-17 19:32
> @jodygarnett
> Is this a duplicate of #212?

Yes I think it is, I will close.

Although I am not sure what other thesauri wish to be synchronized.

**Comment by jodygarnett** [comment] 2021-05-20 15:43
Notes:

* Bo did this previously, had to change linefeed characters for branch.

@wangf1122 can have a look at this!

**Comment by ianwallen** [comment] 2021-05-20 16:32
This task is to sync to use the list from the following

https://canada.multites.net/cst/index.htm

I believe this also contains the list

https://open.canada.ca/data/en/dataset/d4a0e406-eea9-41a7-bcae-28c31f3b9c65

**Comment by ianwallen** [comment] 2021-07-27 13:19
@wangf1122 
Based on conversation with @josegar74, it seems like it would be a good idea to add versioning information in the files so that in the future we can identify the core subject thesaurus that we are using.   We can probably add this as a XML comment in the document.

**Comment by wangf1122** [comment] 2021-07-27 13:47
@ianwallen 
New PR for the versioning https://github.com/metadata101/iso19139.ca.HNAP/pull/232

**Closed as completed** 2021-07-27 16:35 UTC
